# Setup
title: 记忆碎片
tagline: 
url: https://2f0.cn
paginate: 1
baseurl: ""
permalink: :title/

# set timezone
timezone: Asia/Shanghai

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts author_name
author_name:
  name: Eilgnaw
  email: mail@eilganw.com
  web: https://2f0.cn

# Custom vars
version: 1.5.1
github:
  repo: https://github.com/eilgnaw/2f0web
